apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wildcard-cert
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dummy.lab.jjh.us`)
      kind: Rule
      services:
        - name: traefik
          port: 9000
  tls:
    certResolver: letsencrypt
    domains:
      - main: "lab.jjh.us"
        sans:
          - "*.lab.jjh.us"
